version: '3.8'

x-dev:
  &proxy_conf
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"

services:
  app:
    container_name: ${APP_NAME-anuntatorul}_app
    image: node:14
    environment:
      << : *proxy_conf
      CHOKIDAR_USEPOLLING: "true"
      TS_NODE_TRANSPILE_ONLY: "true"
      http_proxy: "${HTTP_PROXY}"
      https_proxy: "${HTTPS_PROXY}"
    working_dir: /app
    ports:
      - 3012:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    restart: on-failure
    command: tail -f /dev/null

  db:
    container_name: ${APP_NAME-anuntatorul}_db
    image: postgres
    environment:
      << : *proxy_conf
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: anuntatorul
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
      - 54311:5432
    restart: on-failure
      
volumes:
  db-data:
    name: ${APP_NAME-anuntatorul}_db